#ifndef DEFINES_H
#define DEFINES_H

#define BUF_SIZE 4096
#define CLIENTS_MAX_COUNT 64
#define CASUAL_PORT 53000
#define IP_PROTO AF_INET
#define TIME_PAUSE 5000

#define SERVER_INITIALIZATION_ERROR 100
#define RECEIVING_ERROR 101
#define SHORT_MESSAGE_ERROR 102
#define ROOM_ID_ERROR 103
#define CONTROL_SUM_ERROR 104
#define UNKNOWN_MES_ID_ERROR 105
#define CLIENTS_LIMIT_ERROR 106
#define REPEATATIVE_REQUEST_ERROR 107
#define CLOSED_ROOM_REQUEST_ERROR 108
#define MESSAGE_SIZE_ERROR 109
#define PRIVACY_ERROR 110

#define RESEND_MESSAGE_ID 1
#define TEXT_MESSAGE_ID 2
#define CONNECT_MESSAGE_ID 3
#define ERROR_MESSAGE_ID 4
#define SUCCESS_MESSAGE_ID 5
#define EXIT_ROOM_MESSAGE_ID 6
#define CHANGE_NAME_MESSAGE_ID 7
#define ROLE_MESSAGE_ID 8
#define STAGE_MESSAGE_ID 9
#define CHECK_CONNECTION_MESAGE_ID 10

#define WAITING_STAGE 0
#define SPEAKING_STAGE 1
#define NIGHT_STAGE 2;
#define ARGUMENT_STAGE 3
#define DEATH_STAGE 4
#define RESULT_STAGE 5

#define CIVILLIAN_ROLE 0
#define MAFIA_ROLE 1
#define MAX_ROLE_ID 2



#endif // DEFINES_H
