#ifndef DEFINES_H
#define DEFINES_H

#define BUF_SIZE 4096
#define CLIENTS_MAX_COUNT 64
#define CASUAL_PORT 54000
#define SERVER_INITIALIZATION_ERROR 100
#define IP_PROTO AF_INET
#define RECEIVING_ERROR 101
#define SHORT_MESSAGE_ERROR 102
#define ROOM_ID_ERROR 103
#define CONTROL_SUM_ERROR 104
#define RESEND_MESSAGE_ID 1

#endif // DEFINES_H
